### ISSUE TITLE
`pip3 install -r requirements.txt` failed for me (in a virtualenv)

### ISSUE THREAD

**Issue by utaal** [secure-foundations/mariposa#10]
This is in a virtualenv created with `python3 -m venv` (I prefer not installing python packages globally).

Installing dependencies failed with:
```
  Downloading pandas-1.3.3.tar.gz (4.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 67.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/Users/redacted/Src/mariposa/venv3/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Users/redacted/Src/mariposa/venv3/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/redacted/Src/mariposa/venv3/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/rv/r1tp_rss7sxg6dlqdqyk6tnh0000gq/T/pip-build-env-n_2fy48_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/rv/r1tp_rss7sxg6dlqdqyk6tnh0000gq/T/pip-build-env-n_2fy48_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/rv/r1tp_rss7sxg6dlqdqyk6tnh0000gq/T/pip-build-env-n_2fy48_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/rv/r1tp_rss7sxg6dlqdqyk6tnh0000gq/T/pip-build-env-n_2fy48_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 18, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
```

I then installed `numpy` manually with `pip3 install numpy` and tried again, but `pip` got stuck trying many version of pandas for this `INFO: pip is looking at multiple versions of pandas to determine which version is compatible with other requirements. This could take a while.`

**Comment by utaal** [comment]
I tried installing the packages manually (without specifying a version), and that succeeded, and installed these (shown from `pip3 freeze`):

```
contourpy==1.1.0
cycler==0.11.0
fonttools==4.41.1
kiwisolver==1.4.4
matplotlib==3.7.2
numpy==1.25.1
packaging==23.1
pandas==2.0.3
patsy==0.5.3
Pillow==10.0.0
plotly==5.15.0
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2023.3
scipy==1.11.1
six==1.16.0
statsmodels==0.14.0
tabulate==0.9.0
tenacity==8.2.2
tqdm==4.65.0
tzdata==2023.3
```

With these, trying mariposa fails with:

```
  File "/Users/redacted/Src/mariposa/scripts/runner.py", line 215, in _run_workers
    print(f"[INFO] {self.task_queue.qsize() + self.exp.num_procs} tasks queued")
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/queues.py", line 126, in qsize
    return self._maxsize - self._sem._semlock._get_value()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError
```
